version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - '3080:80'
      - '3443:443'
    hostname: barcode
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      # - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - barcode

  phpfpm:
    image: 'sthpratik/phpbarcodegenerator:latest'
    # ports:
    #   - '9000:9000'
    networks:
     - barcode

networks:
  barcode:
    name: barcode