version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - '3080:80'
      - '3443:443'
    hostname: barcode
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./src:/etc/nginx/html
    networks:
      - barcode

  phpfpm:
    image: 'phpbarcodegenerator:latest'
    volumes:
      - ./src:/app
    build:
      dockerfile: ./Dockerfile
    networks:
     - barcode

networks:
  barcode:
    name: barcode